In [1]:
import numpy as np

In [2]:
ar = np.array([20, 30, 10, 40, 50, 60, 70, 80, 90, 10])
i = ar[0]
print(i)
print(ar[1])
print(np.where(ar==40)) # Finds the index of an element
print(np.where(ar>=40))

20
30
(array([3]),)
(array([3, 4, 5, 6, 7, 8]),)


In [3]:
ar2 = np.array([[2, 1, 3], [4, 6, 5], [9, 8, 7], [10,11,12]])
i = ar2[0][0]
print(i)
print(ar2[1][2])
print(np.where(ar2==[4,5,6]))
print(np.where(ar2==[4,6,5])) #4 at [1][0], 6 at [1][1], 5 at [1][2]

2
5
(array([1]), array([0]))
(array([1, 1, 1]), array([0, 1, 2]))


In [4]:
arso = np.sort(ar)
print(arso)
ar2so = np.sort(ar2)
print(ar2so)

[10 10 20 30 40 50 60 70 80 90]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
arsl = ar[:5]
print(arsl)
arsl = ar2[1:][1:]
print(arsl)
arsl = ar2[1:,1:]
print(arsl)

[20 30 10 40 50]
[[ 9  8  7]
 [10 11 12]]
[[ 6  5]
 [ 8  7]
 [11 12]]


In [6]:
print(ar.shape)
print(ar2.shape)
r_ar = ar.reshape(2,5) #.reshape(a, b) a = No of subarrays, b = No of elements in each array
print(r_ar)
r_ar2 = ar2.reshape(3,4)
print(r_ar2)

(10,)
(4, 3)
[[20 30 10 40 50]
 [60 70 80 90 10]]
[[ 2  1  3  4]
 [ 6  5  9  8]
 [ 7 10 11 12]]


In [7]:
ar_j = [100, 110, 120]
j_ar = np.concatenate((ar,ar_j))
print(j_ar)
s_ar = np.array_split(ar, 5)
print(s_ar)

[ 20  30  10  40  50  60  70  80  90  10 100 110 120]
[array([20, 30]), array([10, 40]), array([50, 60]), array([70, 80]), array([90, 10])]


In [8]:
from scipy import stats
mn = np.mean(ar)
med = np.median(ar)
mode = stats.mode(ar)
print("Mean", mn)
print("Median", med)
print("Mode", mode)

Mean 46.0
Median 45.0
Mode ModeResult(mode=np.int64(10), count=np.int64(2))


In [9]:
for i in ar:
    print(i)

20
30
10
40
50
60
70
80
90
10


In [10]:
for i in ar2:
    for j in i:
        print(j)

2
1
3
4
6
5
9
8
7
10
11
12
